print("Enter Numbers That You Want To Add")
num1 = int(input("Enter First Number:"))
num2 = int(input("Enter Second Number:"))
print(num1 + num2)
print("Enter Numbers That You Want To Subtract")
num1 = int(input("Enter A Number:"))
num2 = int(input("Enter Another Number:"))
print(num1 - num2)
print("Enter Numbers That You Want To Multiply")
num1 = int(input("Enter A Number:"))
num2 = int(input("Enter Another Number:"))
print(num1 * num2) 
print("Enter Numbers That You Want To Divide")
num1 = int(input("Enter A Number:"))
num2 = int(input("Enter Another Number:"))
print(num1 / num2)